language: python
os:
- linux
services:
- docker
python:
- '3.6'
install:
- pip install .
script: 'true'
deploy:
- provider: script
  script: "./devel/travis_deploy.sh"
  on:
    tags: true
  skip_cleanup: true
env:
  global:
  - secure: flMXhplvgOSb28JbKApBnHVmpPB347el4arHWGLWC/8dkj3LMJ0mUK/C3HYhSYLAy1D8+IcQ7S62N20yIMbMbWkVCN9BNM+pPNBuIZWgYKlI/KjOmqUZZ87TdONzckmMv9cGeHlKEbHl0qGwP/DeIhsW6XxzcHqXUWLoJ2v1CKstyC2Rt/gAeYzzOGyz0XuSk8R+xCRixgHX+5MySnqIT6irbMzlMYic6JiT9CoU+z32xpLKNrIagVpzaoD6oVrJz3rjq4JHrNZBPCn6QlFf09mQc/TT4cRiu1YayeI35j/zgkFRacwYyANPUIePtf3zyN2SzrHFGKXBsRfTHZ9C2QrcIIu3mkoZjdCovXNlwtntwepHq9sp98IEvPUnKEiy7M5OKyZr/HRcEIg2HaSbcovSfCp7wml9cizbPalIz0qxC7l/cp23neLFXhSPVQ6elgdMMPC0OxX3RF7Y5h4ib3hdFqlduedoV9Nbq6Kcq1W/DWEdSYy2L1GT8zcmuWyUj3IXaVapn5D3aObY4g89XNTzRY39YtcfXn7VKmDggAjwCn7C+pX4e+YOW34MLoKvlUQNYc64HJIHQHDUoPR8ersS6L+zkSIE0j1bloAalXj7XaPaEQyz5JqNOmB9ZoQ/Y4x+WPCmRUBNo44NgaPQNkaCbI4+T17I7EOAQkbK0Ns=
  - secure: Zm0hIVHFMChAZxwGLU8MoQp52hIsYbasDJoUSc4DYBQCOFzLT+ZR/CLEfnEl3Tq3Zbg+1OQ/Sb+FkFQueyPG8C4KHGhOU94vT9tq9Fors+bFZMK+H2ae3GtSziBoWYomu69DcGJtuoeRsL79bfGuDzq8wDXeJVjSWpLfwh6v5VWf554wSk+cdx17N+C09AMTdoAVc7OLpEa+zuk4lf5k2AZbBUU0nkejaRYADnB9nMilgK1igLcprx+yk9NKt+mdMi6TWgJ7wgwoebApjIrxS5HbrhLxuoi/p+e4JNDcqoT0a1hfWnEXL8M7ZHVv8dPLsfXOOD9Bur1rVOh+GqQwhUm8fIORMfoNHOh/u35eJGZyBjqyRZSgWE9AD+/EVrjRSbKce6HcM9Qr/BmI/QEuNa6zGehcRxT2jGkSbaNZHhmPOJi8GTiZarUrX7sLHPw9JF7IZHNxWCWtIOnATua9JTOXABPiIzRCLb6WnUVuFbOiQbIurVT9FNyvG/eO/rwlyj23EPDvC7l6jujh9T7qtREc9E89UjaCPsZ+e74DxvGGM91f2CPdN0o1VnKmg8XtujDFDljmWhGkwlEB5QC/KEVpkwD9pks4Ls/vT8PS5LqEGOc2rfXyBzyHlMMrh/R3ZNV0Oxx3YEeMCz4AP2gHgUQyTy40cmdSUq4Vhigih80=
  - secure: b1/Fo8hmtq0dQuHv9zCr3gH9jrmelHqkzsqejtukP5Q/H/lEHOpNQZOb13n5i3+HJn0hrjR8ZfxndZ7Ni/qKlc6REAjAkWNO8jvipdY1MDFsWnslk7KcM1hAgN1Wbp5vWHJGipbyDdpYxZUD6nCn7gt8iAsyMfVmkdk9IBEVo4/mNfhkqngdCqFX4yLq8SEFiXqL6ZJK9jg+8T1TKJzEK4a3qyZ0AhM4PlLngqI2DPfXwp+/v4K0K/KZ7mwHKT9fiU8U2/jPSnzhT6wFVUTCkYHE9EUeejIv8q8QWg08kmWoZxZE1r4WvOzJrVOhwAzDhvjT0VMoxW5COKfLWaM4lA4Q593IQm2q+g9MAc/3T7flWZO5QZ7LNUd+sekoAGqppdbeEfpRDjlLT+XiNNABWhDN8lRlhHybffxsyi3L0r74kVCr9hItHelDF8Zi6SwgvblXg8gQm2I4YrqrMUkpNS96LHyZCCgcPIkS/7Bz9rZcnDfA3sooIriiVOn9xt/D5fCcM2esgi51iaWiC4jHRCwMZRkeNHBE5IXoWetHmKYeC7g3APPgMURhj0wf59chJmf1b+Xv6N1B8ho5UeBkAJ4h6c+0LKkHNpWvzhQPy4iENtvJ5RrsYdCtvbRMEA7xuSJSriJrzKQQcrV/Mc+JYwlDTyEZJrXuWoNquML78p4=
